version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
  build:
    commands:
      - npm run test -- --ci --watchAll=false
      - npm run build

artifacts:
  base-directory: ./build
  files:
    - "**/*"

cache:
  paths:
    - "./node_modules/**/*"
