version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
  build:
    commands:
      - echo Running the unit the tests...
      - npm run test --watchAll=false --updateSnapshot
      - echo Testing has completed ...
      - echo Running the build  ...
      - npm run build
      - echo Build has completed ...

artifacts:
  base-directory: ./build
  files:
    - "**/*"

cache:
  paths:
    - "./node_modules/**/*"
